import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch design system tokens
        primary:                  '#340075',
        secondary:                '#b5005d',
        tertiary:                 '#2e007b',
        background:               '#f8f9ff',
        surface:                  '#f8f9ff',
        'surface-bright':         '#f8f9ff',
        'surface-dim':            '#d1daec',
        'surface-variant':        '#dae3f5',
        'surface-container':      '#e6eeff',
        'surface-container-low':  '#eff4ff',
        'surface-container-high': '#e0e9fa',
        'surface-container-highest': '#dae3f5',
        'surface-container-lowest': '#ffffff',
        'surface-tint':           '#6f46b9',
        'on-surface':             '#131c29',
        'on-surface-variant':     '#4a4452',
        'on-primary':             '#ffffff',
        'on-secondary':           '#ffffff',
        'on-tertiary':            '#ffffff',
        'on-background':          '#131c29',
        'primary-container':      '#4c1d95',
        'primary-fixed':          '#ebdcff',
        'primary-fixed-dim':      '#d3bbff',
        'secondary-container':    '#da2676',
        'secondary-fixed':        '#ffd9e2',
        'secondary-fixed-dim':    '#ffb1c7',
        'tertiary-container':     '#442591',
        'tertiary-fixed':         '#e8ddff',
        'tertiary-fixed-dim':     '#cebdff',
        'inverse-primary':        '#d3bbff',
        'inverse-surface':        '#28313e',
        'inverse-on-surface':     '#ebf1ff',
        'on-primary-container':   '#b994ff',
        'on-primary-fixed':       '#260059',
        'on-primary-fixed-variant': '#572ba0',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed':     '#3f001c',
        'on-secondary-fixed-variant': '#8e0048',
        'on-tertiary-container':  '#b197ff',
        'on-tertiary-fixed':      '#21005e',
        'on-tertiary-fixed-variant': '#4f319c',
        outline:                  '#7b7483',
        'outline-variant':        '#ccc3d4',
        error:                    '#ba1a1a',
        'on-error':               '#ffffff',
        'error-container':        '#ffdad6',
        'on-error-container':     '#93000a',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['"Space Grotesk"', 'sans-serif'],
        sans:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      animation: {
        'pulse-dot': 'pulse 1.5s ease-in-out infinite',
        'slide-in-right': 'slideInRight 0.25s ease-out',
        'slide-in-up': 'slideInUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
      },
      keyframes: {
        slideInRight: {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        slideInUp: {
          from: { transform: 'translateY(100%)' },
          to: { transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      boxShadow: {
        'primary': '0 4px 20px rgba(52, 0, 117, 0.25)',
        'card': '0 4px 20px rgba(30, 39, 52, 0.06)',
        'panel': '-10px 0 30px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}

export default config
